services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_USER: chilli
      MSSQL_DB: main
      MSSQL_PASSWORD: S3cur3P@ssw0rd!
      MSSQL_SA_PASSWORD: Str0ngP@ssw0rd!
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: chilli
      POSTGRES_PASSWORD: S3cur3P@ssw0rd!
      POSTGRES_DB: main
    ports:
      - "5432:5432"