services:
  postgres:
    image: postgres:latest
    container_name: pg-main
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chilli
      POSTGRES_PASSWORD: "S3cur3P@ssw0rd!"
      POSTGRES_DB: main
    volumes:
      - pg_main_data:/var/lib/postgresql
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-main
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
    volumes:
      - mssql_main_data:/var/opt/mssql

volumes:
  pg_main_data:
  mssql_main_data:
