services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: chilli
      POSTGRES_DB: main
      POSTGRES_PASSWORD: S3cur3P@ssw0rd!
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql:rw,noexec,nosuid,size=512m
