services:
  # Microsoft SQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_USER: "chilli"
      MSSQL_DB: "main"
      MSSQL_PASSWORD: "S3cur3P@ssw0rd!"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "chilli"
      POSTGRES_PASSWORD: "S3cur3P@ssw0rd!"
      POSTGRES_DB: "main"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mssql_data:
  postgres_data: