services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_USER: chilli
      MSSQL_DB: main
      MSSQL_PASSWORD: S3cur3P@ssw0rd!
      MSSQL_SA_PASSWORD: Dek!05$q@A^T
    ports:
      - 1433

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: chilli
      POSTGRES_DB: main
      POSTGRES_PASSWORD: S3cur3P@ssw0rd!
    ports:
      - 5432